name: esquema-parcial-frontend

x-backend: &backend
  env_file:
    - ../backend/.env
    - TZ=Europe/Madrid

services:
  frontend:
    build:
      context: .
    environment:
      NODE_ENV: production
      TZ: Europe/Madrid
    container_name: frontend
    ports:
      - 4200:4200
